services:
  pg1-primary:
    image: postgres:17
    container_name: pg1-primary
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ChangeMe1
      - POSTGRES_DB=postgres
      - REPLICATION_USER=repl_user
      - REPLICATION_PASSWORD=repl_pass1
    ports:
      - "55432:5432"
    command:
      - postgres
      - -c
      - wal_level=replica
      - -c
      - max_wal_senders=10
      - -c
      - max_replication_slots=10
      - -c
      - hot_standby=on
    volumes:
      - pgcluster1_primary_data:/var/lib/postgresql/data
      - ./primary-init:/docker-entrypoint-initdb.d

  pg1-replica:
    image: postgres:17
    container_name: pg1-replica
    depends_on:
      - pg1-primary
    environment:
      - PGDATA=/var/lib/postgresql/data
      - REPLICATION_USER=repl_user
      - REPLICATION_PASSWORD=repl_pass1
      - PRIMARY_HOST=pg1-primary
    volumes:
      - pgcluster1_replica_data:/var/lib/postgresql/data
      - ./replica-init/replica-entrypoint.sh:/usr/local/bin/replica-entrypoint.sh
    entrypoint:
      - bash
      - /usr/local/bin/replica-entrypoint.sh

volumes:
  pgcluster1_primary_data: {}
  pgcluster1_replica_data: {}
